[[- $dot := .]]
[[- $d   := .TD.Data]]
[[- $dn  := .TD.Data.TitledName]]
# Generate a minimal Docker container with [[$d.Name]] installed            

FROM golang:latest AS golang
LABEL maintainer="bob@2kranki.us"
ENV GOLANG_DOCKER_CONTAINER=1
ENV CGO_ENABLED=0
ENV GOOS=linux
RUN apt-get update && apt-get install --yes sqlite3 libsqlite3-dev 
RUN go get github.com/2kranki/jsonpreprocess \
    && go get github.com/2kranki/go_util \
    && go get github.com/shopspring/decimal \
    && go get [[$d.Plugin.Plugin.GenImportString]]
WORKDIR /go/src
COPY ./src/* ./
RUN go build -o /go/bin/[[$d.Name]] .                                       
RUN ls -al /go/bin/

FROM alpine:latest AS production
WORKDIR /usr/local/bin/
COPY --from=golang /go/bin/[[$d.Name]] .                                    
EXPOSE 8090
CMD ["[[$d.Name]]"]                                                         

